pub(crate) mod automation;
pub(crate) mod completion;
pub(crate) mod extensions;
pub(crate) mod interactive;
pub(crate) mod links;
mod model_picker;
pub(crate) mod sandbox;
pub(crate) mod setup;
mod setup_style;
pub(crate) mod slash;
pub(crate) mod workspace;
