#!/usr/bin/env python3
"""Fail when a repository Markdown file contains a broken local link."""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
LINK = re.compile(r"!?\[[^\]]*]\(([^)\s]+)(?:\s+[^)]*)?\)")
SCHEME = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")


def is_generated_documentation_mirror(path: Path) -> bool:
    relative = path.resolve().relative_to(ROOT).parts
    return relative[:2] == ("docs-site", "content") or relative[:4] == (
        "release",
        "community",
        "docs-site",
        "content",
    )


def archive_files() -> list[Path]:
    # These are generated by supported build/test entrypoints, never project
    # documentation. Do not descend through symlinks in an extracted archive.
    generated = {".git", ".work", "node_modules", ".vscode-test", ".gradle",
                 ".intellijPlatform", "__pycache__", "target", "dist"}
    files = []
    for directory, names, filenames in os.walk(ROOT, followlinks=False):
        parent = Path(directory)
        names[:] = [name for name in names if name not in generated
                    and not (parent / name).is_symlink()
                    and (parent / name).relative_to(ROOT).parts != ("clients", "jetbrains", "build")]
        files.extend(parent / name for name in filenames
                     if name.endswith(".md") and not (parent / name).is_symlink()
                     and not is_generated_documentation_mirror(parent / name))
    return sorted(files)


def default_files() -> list[Path]:
    if not (ROOT / ".git").exists():
        return archive_files()
    result = subprocess.run(
        [
            "git",
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            "*.md",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return sorted(
        {
            ROOT / name
            for name in result.stdout.splitlines()
            if name
            and (ROOT / name).is_file()
            and not is_generated_documentation_mirror(ROOT / name)
        }
    )


def requested_files(arguments: list[str]) -> list[Path]:
    if not arguments:
        return default_files()

    candidates = default_files()
    files: list[Path] = []
    for argument in arguments:
        path = (ROOT / argument).resolve()
        if path.is_dir():
            files.extend(candidate for candidate in candidates if candidate.is_relative_to(path))
        elif not is_generated_documentation_mirror(path):
            files.append(path)
    return files


def main() -> int:
    failures: list[str] = []
    files = requested_files(sys.argv[1:])

    for source in files:
        if not source.is_file():
            failures.append(f"{source.relative_to(ROOT)}: file does not exist")
            continue
        for line_number, line in enumerate(
            source.read_text(encoding="utf-8").splitlines(), start=1
        ):
            for match in LINK.finditer(line):
                raw = match.group(1).strip("<>")
                destination = unquote(raw.split("#", 1)[0])
                if (
                    not destination
                    or destination.startswith("/")
                    or SCHEME.match(destination)
                ):
                    continue
                target = (source.parent / destination).resolve()
                if not target.exists():
                    failures.append(
                        f"{source.relative_to(ROOT)}:{line_number}: "
                        f"broken local link {raw!r}"
                    )

    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1

    print(f"validated local links in {len(files)} Markdown files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
