// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Scope } from "./Scope";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateTurn = { scope: Scope, content: JsonValue, attachment_ids: Array<Id>, generate_title: boolean, };
