import Foundation
import DesktopCore

enum WorkingEfficiencyChecks {
    static func run() throws {
        let source = "diff --git a/file.txt b/file.txt\n--- a/file.txt\n+++ b/file.txt\n@@ -10,2 +10,3 @@\n context\n-old\n+new\n+extra\ndiff --git a/deleted b/deleted\ndeleted file mode 100644\n--- a/deleted\n+++ /dev/null\n@@ -1 +0,0 @@\n-gone\n"
        let diff = UnifiedDiff(source)
        try expectEqual(diff.files.count, 2); try expectEqual(diff.files[0].title, "file.txt"); try expectEqual(diff.files[1].title, "deleted")
        try expectEqual(diff.additions, 2); try expectEqual(diff.removals, 2); try expectFalse(diff.truncated)
        let added = diff.files[0].lines.filter { $0.kind == .addition }
        try expectEqual(added.map(\.newLine), [11, 12]); try expectEqual(added.map(\.oldLine), [nil, nil])
        try expectEqual(diff.files[0].lines.first { $0.kind == .removal }?.oldLine, 11)
        try expectTrue(UnifiedDiff("").files.isEmpty)
        try expectTrue(UnifiedDiff("", serverTruncated: true).truncated)
        try expectTrue(UnifiedDiff(source, maxFiles: 1).truncated)
        try expectEqual(UnifiedDiff(source, maxFiles: 1).files.count, 1)
        try expectTrue(UnifiedDiff(source, maxLines: 4).truncated)
        try expectEqual(UnifiedDiff(source, maxLines: 4).files[0].lines.count, 4)
        try expectTrue(UnifiedDiff("🌱🌱", maxBytes: 4).truncated)
        try expectEqual(UnifiedDiff("🌱🌱", maxBytes: 4).raw, "🌱")
        let long = UnifiedDiff(String(repeating: "x", count: 9000))
        try expectTrue(long.truncated); try expectTrue(long.files[0].lines[0].text.count < 4200)
        let binary = UnifiedDiff("diff --git a/image.png b/image.png\nBinary files a/image.png and b/image.png differ\n")
        try expectEqual(binary.additions, 0); try expectEqual(binary.files.count, 1)
        let scope = Scope(profileID: "a")
        let context = TurnInputContext(profileID: "connection-a", provider: "configured", endpoint: "https://example.test/v1", scope: scope.json)
        let foreignContext = TurnInputContext(profileID: "connection-b", provider: "configured", endpoint: "https://other.test/v1", scope: scope.json)
        let foreignOrganization = TurnInputContext(profileID: "connection-a", provider: "configured", endpoint: "https://example.test/v1", scope: scope.json.replacing("organization_id", with: .string("other-org")))
        var attempts = TurnInputAttempts()
        let first = attempts.begin(context: context, session: "session", target: "turn", mode: .queue, content: "keep this")
        let retry = attempts.begin(context: context, session: "session", target: "new-turn", mode: .queue, content: "keep this")
        try expectEqual(first, retry) // A lost ACK never becomes a new request after selection/retry.
        let another = attempts.begin(context: foreignContext, session: "session", target: "turn", mode: .queue, content: "keep this")
        try expectNotEqual(another.key, first.key)
        try expectNotEqual(attempts.begin(context: foreignOrganization, session: "session", target: "turn", mode: .queue, content: "keep this").key, first.key)
        let otherSession = attempts.begin(context: context, session: "other", target: "turn", mode: .queue, content: "keep this")
        try expectNotEqual(otherSession.key, first.key)
        let value: JSON = .object(["scope": scope.json, "id": .string("input"), "session_id": .string("session"), "target_turn_id": .string("turn"), "mode": .string("queue"), "content": .string("keep this"), "idempotency_key": .string(first.key), "status": .string("pending")])
        let accepted = try TurnInputRecord(value, scope: scope, sessionID: "session")
        try expectTrue(first.accepts(accepted))
        try expectEqual(attempts.acknowledgedDraft(context: context, session: "session", record: accepted), "keep this")
        try expectEqual(DraftSubmission.acknowledged(current: "newer draft", submitted: attempts.acknowledgedDraft(context: context, session: "session", record: accepted)!), "newer draft")
        try expectThrows(try TurnInputRecord(value, scope: Scope(profileID: "b"), sessionID: "session"))
        try expectThrows(try TurnInputRecord(value, scope: scope, sessionID: "other"))
        try expectFalse(first.accepts(try TurnInputRecord(value.replacing("idempotency_key", with: .string("wrong")), scope: scope, sessionID: "session")))
        attempts.acknowledge(context: foreignContext, session: "session", record: accepted)
        try expectEqual(attempts.begin(context: context, session: "session", target: "turn", mode: .queue, content: "keep this").key, first.key)
        attempts.acknowledge(context: context, session: "session", record: accepted)
        try expectNotEqual(attempts.begin(context: context, session: "session", target: "turn", mode: .queue, content: "keep this").key, first.key)
        try expectTrue(try TurnInputRecord.list(.array([value.replacing("status", with: .string("consumed"))]), scope: scope, sessionID: "session").isEmpty)
        try expectThrows(try TurnInputRecord.list(.array([value, value]), scope: scope, sessionID: "session"))
        try expectTrue(attempts.hasUnconfirmed(context: context, session: "session", content: "keep this"))
        attempts.discard(context: context, session: "session", content: "keep this")
        try expectFalse(attempts.hasUnconfirmed(context: context, session: "session", content: "keep this"))
        try expectTrue(attempts.hasUnconfirmed(context: foreignContext, session: "session", content: "keep this"))
        let whitespace = attempts.begin(context: context, session: "whitespace", target: "turn", mode: .queue, content: "keep this", originalDraft: "  keep this\n")
        let whitespaceRecord = try TurnInputRecord(value.replacing("session_id", with: .string("whitespace")).replacing("idempotency_key", with: .string(whitespace.key)), scope: scope, sessionID: "whitespace")
        let confirmedDraft = attempts.acknowledgedDraft(context: context, session: "whitespace", record: whitespaceRecord)!
        try expectEqual(DraftSubmission.acknowledged(current: "  keep this\n", submitted: confirmedDraft), "")
        try expectEqual(DraftSubmission.acknowledged(current: "new instruction", submitted: confirmedDraft), "new instruction")
        var gate = TurnInputReadGate()
        let old = gate.begin(), current = gate.begin()
        try expectFalse(gate.accepts(old)); try expectTrue(gate.accepts(current))
        gate.invalidate() // Mutation or scope/selection switch.
        try expectFalse(gate.accepts(current))
        let beforeSnapshot = gate.begin(); gate.invalidateRequests(); try expectFalse(gate.accepts(beforeSnapshot))
        let turn: JSON = .object(["id": .string("turn"), "session_id": .string("session"), "status": .string("calling_model")])
        try expectEqual(TurnInputTarget.active(turns: [turn], sessionID: "session"), turn)
        try expectTrue(TurnInputTarget.canSteer(turn))
        try expectFalse(TurnInputTarget.canSteer(turn.replacing("status", with: .string("awaiting_approval"))))
        try expectEqual(TurnInputTarget.active(turns: [turn.replacing("status", with: .string("completed"))], sessionID: "session"), nil)
        try expectEqual(TurnInputTarget.active(turns: [turn.replacing("checkpoint", with: .object(["execution_mode": .string("manual_tool")]))], sessionID: "session"), nil)
        try expectEqual(TurnInputTarget.active(turns: [turn, turn.replacing("id", with: .string("other"))], sessionID: "session"), nil)
        print("PASS: bounded diff files/hunks/line numbers, Unicode/truncation, scoped queue acknowledgements, retry idempotency, stale read barriers and eligible targets")
    }
}
